name: bern03 - Asifa
channels: [conda-forge]
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - geopandas
  - cartopy
  - shapely
  - fiona
  - pyproj
python -m pip show numpy pandas scikit-learn seaborn