name: bern03-climate-Asifa
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - xarray
  - netcdf4
  - dask
  - matplotlib
  - cartopy
  - seaborn
  - cmocean
  - jupyterlab
  - ipykernel
  - tqdm
  - statsmodels
  - scikit-learn
  - pip
  - pip:
      - eofs